### ISSUE TITLE
Add common validation rules

### ISSUE THREAD

**Issue by isneezy** [isneezy/confere.js#1]
To be usable library there is a need to add some common used validation rules
- [x] After (date)
- [x] After or Equal (date)
- [x] Alpha
- [x] Alpha Dash
- [x] Alpha Numeric
- [x] Before (date)
- [x] Before or Equal (date)
- [x] Between
- [x] Boolean
- [x] Digits
- [x] Digits Between
- [x] integer
- [x] Url

**Comment by iamzjohn** [comment]
I will handle this feature
